name: Telegram Notify

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, ready_for_review]

jobs:
  notify:
    uses: zariavv/.github/.github/workflows/notify-telegram.yml@main
    with:
      topic_id: "2"
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
